version: '3'
services:
  tests:
    platform: linux/amd64
    build: .
    environment:
      DEBUG: "True"
      PYTHONPATH: /opt/app
      TEST_SYSTEM_HOST:
      TEST_SYSTEM_USERNAME:
      TEST_SYSTEM_PASSWORD:
      TEST_SYSTEM_SCHEMA:
