# +--------------------------------------------------------------------------+
# |  Licensed Materials - Property of IBM                                    |
# |                                                                          |
# | (C) Copyright IBM Corporation 2009-2018.                                 |
# +--------------------------------------------------------------------------+
# | This module complies with Django 1.0 and is                              |
# | Licensed under the Apache License, Version 2.0 (the "License");          |
# | you may not use this file except in compliance with the License.         |
# | You may obtain a copy of the License at                                  |
# | http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable |
# | law or agreed to in writing, software distributed under the License is   |
# | distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY |
# | KIND, either express or implied. See the License for the specific        |
# | language governing permissions and limitations under the License.        |
# +--------------------------------------------------------------------------+
# | Authors: Rahul Priyadarshi, Hemlata Bhatt, Vyshakh A                     |
# +--------------------------------------------------------------------------+

import copy
import datetime
from os import write
import uuid

try:
    from django.db.backends.schema import BaseDatabaseSchemaEditor
except ImportError:
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from django.db import models
from django.db.backends.utils import truncate_name
from django.db.models.fields.related import ManyToManyField
from django import VERSION as djangoVersion
from django.conf import settings
from . import Database

Error = Database.Error


class DB2SchemaEditor(BaseDatabaseSchemaEditor):
    psudo_column_prefix = 'psudo_'
    sql_delete_table = "DROP TABLE %(table)s"
    sql_rename_table = "CREATE TABLE %(new_table)s AS (SELECT * FROM %(old_table)s) WITH DATA; DROP TABLE %(old_table)s"
    sql_create_column = "ALTER TABLE %(table)s ADD COLUMN %(column)s %(definition)s"
    sql_alter_column_type = "ALTER COLUMN %(column)s SET DATA TYPE %(type)s"
    #sql_alter_column_type = (" ADD COLUMN %(column)s_new %(type)s;"  # The prefix ALTER TABLE is al ready added 
    #                         " UPDATE %(table)s SET %(column)s_new = CAST(%(column)s AS %(type)s);"
    #                         " COMMIT;"
    #                         " ALTER TABLE %(table)s DROP COLUMN %(column)s;"
    #                         " ALTER TABLE %(table)s ADD COLUMN %(column)s %(type)s;"
    #                         " UPDATE %(table)s SET %(column)s = %(column)s_new;"
    #                         " COMMIT;"
    #                         " ALTER TABLE %(table)s DROP COLUMN %(column)s_new"
    #                        )
    #sql_alter_column_null = (" ADD COLUMN %(column)s_new %(type)s;"  # The prefix ALTER TABLE is al ready added 
    #                         " UPDATE %(table)s SET %(column)s_new = CAST(%(column)s AS %(type)s);"
    #                         " COMMIT;"
    #                         " ALTER TABLE %(table)s DROP COLUMN %(column)s;"
    #                         " ALTER TABLE %(table)s ADD COLUMN %(column)s %(type)s IS NULL;"
    #                         " UPDATE %(table)s SET %(column)s = %(column)s_new;"
    #                         " COMMIT;"
    #                         " ALTER TABLE %(table)s DROP COLUMN %(column)s_new"
    #                        )
    #sql_alter_column_not_null = (" ADD COLUMN %(column)s_new %(type)s;"  # The prefix ALTER TABLE is al ready added 
    #                             " UPDATE %(table)s SET %(column)s_new = CAST(%(column)s AS %(type)s);"
    #                             " COMMIT;"
    #                             " ALTER TABLE %(table)s DROP COLUMN %(column)s;"
    #                             " ALTER TABLE %(table)s ADD COLUMN %(column)s %(type)s NOT NULL;"
    #                             " UPDATE %(table)s SET %(column)s = %(column)s_new;"
    #                             " COMMIT;"
    #                             " ALTER TABLE %(table)s DROP COLUMN %(column)s_new"
    #                            )# ALTER TABLE DEVFILEVDP.PFDCTP ALTER COLUMN DTSB DROP NOT NULL;
    sql_alter_column_type_from_int_to_auto = "ALTER COLUMN %(column)s SET GENERATED BY DEFAULT AS IDENTITY( START WITH %(max)d, INCREMENT BY 1, CACHE 10 ORDER )"
    sql_create_fk = "ALTER TABLE %(table)s ADD CONSTRAINT %(name)s FOREIGN KEY (%(column)s) REFERENCES %(to_table)s (%(to_column)s)"
    sql_delete_pk = "ALTER TABLE %(table)s DROP CONSTRAINT %(name)s"
    sql_delete_unique = "ALTER TABLE %(table)s DROP CONSTRAINT %(name)s"
    sql_drop_pk = "ALTER TABLE %(table)s DROP PRIMARY KEY"
    sql_drop_default = "ALTER TABLE %(table)s ALTER COLUMN %(column)s DROP DEFAULT"
    sql_rename_column = (
        "ALTER TABLE %(table)s ADD COLUMN %(new_column)s %(new_type)s; UPDATE %(table)s SET %(new_column)s = %(old_column)s; COMMIT;  ALTER TABLE %(table)s DROP COLUMN %(old_column)s"
    )
    sql_create_unique = (
        "ALTER TABLE %(table)s ADD CONSTRAINT %(name)s "
        "UNIQUE (%(columns)s)"
    )

    @property
    def sql_create_pk(self):
        self._reorg_tables()
        return "ALTER TABLE %(table)s ADD CONSTRAINT %(name)s PRIMARY KEY (%(columns)s)"

    def prepare_default(self, value):
        return self.quote_value(value)

    def _create_index_name(self, table_name, column_names, suffix=""):
        #Ensure table_name is a string
        if table_name.__class__.__name__ != "str":
            if '"' not in str(table_name.__name__):
                table_name = f'"{table_name.__name__}"'
        index_name = super()._create_index_name(table_name, column_names, suffix=suffix)
        index_name = index_name.replace('.', '_')
        return index_name

    def _base_identifier(self, name: str) -> str:
        """Return the base (non-schema) identifier without quotes."""
        raw = str(name or "").strip()
        if "." in raw:
            raw = raw.split(".")[-1]
        return raw.replace('"', '').strip()

    def _normalize_system_name(self, value) -> str:
        """Normalize db_system_name to an uppercase identifier or empty string."""
        if value is None:
            return ""
        normalized = str(value).strip().upper()
        return normalized

    def execute(self, sql, params=()):
        """Execute SQL statements and fail fast on database errors."""
        statements = str(sql).split(';')
        for stmt in statements:
            stmt = stmt.strip()
            if not stmt:
                continue

            try:
                super().execute(stmt, params=params)

            except Exception:
                raise

    def _apply_nullability_change(self, model, field, make_nullable):
        """Apply nullability change using direct ALTER statements."""
        sql = self.sql_alter_column_null if make_nullable else self.sql_alter_column_not_null
        stmt = self.sql_alter_column % {
            'table': self.quote_name(model._meta.db_table),
            'changes': sql % {'column': self.quote_name(field.column)}
        }
        self.execute(stmt)


    def quote_name(self, name: str) -> str:
        """
        Zorgt ervoor dat zowel library als objectnaam tussen dubbele quotes staan.
        Voorbeeld:
            mylib.mytable -> "MYLIB"."MYTABLE"
            mytable       -> "MYTABLE"
        """
        if "." in name:
            library, table = name.split(".", 1)
            return f'"{library.upper()}"."{table.upper()}"'
        return f'"{name.upper()}"'

    def alter_field(self, model, old_field, new_field, strict=False):
        alter_field_data_type = False
        alter_field_nullable = False
        alter_field_default = False
        alter_field_primary_key = False
        alter_field_name = False
        alter_field_check_constraint = False
        alter_field_unique = False
        alter_field_index = False
        rebuild_incomming_fk = False
        alter_incomming_fk_data_type = False
        deferred_constraints = {
            'pk': {},
            'unique': {},
            'index': {},
            'check': {}
        }

        old_db_field = old_field.db_parameters(connection=self.connection)
        new_db_field = new_field.db_parameters(connection=self.connection)
        old_db_field_type = old_db_field['type']
        new_db_field_type = new_db_field['type']
        if old_field.remote_field is not None and hasattr(old_field.remote_field, 'through'):
            rel_condition = (
                        old_field.remote_field.through and new_field.remote_field.through and old_field.remote_field.through._meta.auto_created and new_field.remote_field.through._meta.auto_created)
        else:
            rel_condition = False

        if ((old_db_field_type, new_db_field_type) == (None, None)) and rel_condition:
            return self._alter_many_to_many(model, old_field, new_field, strict)
        elif old_db_field_type is None or new_db_field_type is None:
            raise ValueError("Cannot alter field %s into %s" % (
                old_db_field,
                new_db_field,
            ))
        # Need to change datatype which need remaking of field
        if (old_db_field_type != new_db_field_type) and (
                isinstance(old_field, (models.AutoField, models.TextField)) or isinstance(new_field, models.TextField)):
            if old_field.primary_key and new_field.primary_key:
                rebuild_incomming_fk = True
                if isinstance(old_field, models.AutoField) and isinstance(new_field, models.IntegerField):
                    pass
                else:
                    alter_incomming_fk_data_type = True
            old_field, new_field = self.alterFieldDataTypeByRemaking(model, old_field, new_field, strict)
            old_db_field = old_field.db_parameters(connection=self.connection)
            new_db_field = new_field.db_parameters(connection=self.connection)
            old_db_field_type = old_db_field['type']
            new_db_field_type = new_db_field['type']
        if old_db_field_type != new_db_field_type:
            alter_field_data_type = True

        if old_field.column != new_field.column:
            alter_field_name = True
        if old_field.db_index != new_field.db_index:
            alter_field_index = True
        if old_field.unique != new_field.unique:
            alter_field_unique = True
        if old_field.primary_key != new_field.primary_key:
            alter_field_primary_key = True
        if old_db_field['check'] != new_db_field['check']:
            alter_field_check_constraint = True
        if old_field.null != new_field.null:
            alter_field_nullable = True
        old_default = DB2SchemaEditor._effective_default(old_field)
        new_default = DB2SchemaEditor._effective_default(new_field)
        if (old_field.default is not None) and old_field.has_default():
            if old_default != new_default:
                alter_field_default = True

        # Need to remove Primary Key
        if alter_field_primary_key and old_field.primary_key:
            if strict:
                pk_names = self._constraint_names(model, [old_field.column], primary_key=True)
                if len(pk_names) == 0:
                    raise ValueError("Found no primary key in %s.%s " % (model._meta.db_table, old_field.column))
            self.execute(
                self.sql_drop_pk % {
                    'table': self.quote_name(model._meta.db_table)
                }
            )

        # Need to remove unique Key
        if alter_field_unique and old_field.unique or (
                old_field.unique and alter_field_primary_key and not old_field.primary_key):
            unique_key_names = self._constraint_names(model, [old_field.column], unique=True)
            if strict and len(unique_key_names) != 1:
                raise ValueError("Found wrong number of unique constraints for (table)s.(column)s" % {
                    'table': model._meta.db_table, 'column': old_field.column
                })

            for unique_key_name in unique_key_names:
                self.execute(
                    self.sql_delete_unique % {
                        'table': self.quote_name(model._meta.db_table),
                        'name': unique_key_name
                    }
                )

        # Need to remove Index
        if alter_field_index and old_field.db_index:
            index_names = self._constraint_names(model, [old_field.column], index=True)
            if strict and len(index_names) != 1:
                raise ValueError("Found wrong number of Indexes for (table)s.(column)s" % {
                    'table': model._meta.db_table, 'column': old_field.column
                })
            for index_name in index_names:
                self.execute(
                    self.sql_delete_index % {
                        'name': index_name
                    }
                )

        # Need to remove check constraint
        if alter_field_check_constraint and old_db_field['check']:
            check_constraint_names = self._constraint_names(model, [old_field.column], check=True)
            if strict and len(check_constraint_names) != 1:
                raise ValueError("Found wrong number of check constraints for (table)s.(column)s" % {
                    'table': model._meta.db_table, 'column': old_field.column
                })
            for check_constraint_name in check_constraint_names:
                self.execute(
                    self.sql_delete_check % {
                        'table': self.quote_name(model._meta.db_table),
                        'name': check_constraint_name
                    }
                )

        # Drop all FK constraints, if require we will make it again
        flag = old_field.remote_field
        if flag:
            fk_names = self._constraint_names(model, [old_field.column], foreign_key=True)
            for fk_name in fk_names:
                self.execute(
                    self.sql_delete_fk % {
                        'table': self.quote_name(model._meta.db_table),
                        'name': fk_name
                    }
                )

        if alter_field_name or alter_field_data_type:
            # Drop all incoming FK constraint, if require we will make it again
            if old_field.primary_key and new_field.primary_key:
                rebuild_incomming_fk = True
                for incoming_fks in old_field.model._meta.get_fields():
                    # Skip BigAutoField --> 'BigAutoField' object has no attribute 'field'
                    #if incoming_fks.get_internal_type() not in ("BigAutoField", "DateTimeField", "OneToOneField", "TextField", "ForeignKey", "CharField", "Db2ActualCharField", "Db2AutoField", "Db2DecimalField"):
                    if hasattr(incoming_fks, 'field'):
                        fk_names = self._constraint_names(incoming_fks.model, [incoming_fks.field.column], foreign_key=True)
                        for fk_name in fk_names:
                            self.execute(
                                self.sql_delete_fk % {
                                    'table': self.quote_name(incoming_fks.model._meta.db_table),
                                    'name': fk_name,
                                }
                            )

            # Defer constraint check
            with self.connection.cursor() as cur:
                constraints = self.connection.introspection.get_constraints(cur, model._meta.db_table)
            self._defer_constraints_check(constraints, deferred_constraints, old_field, new_field, model, defer_pk=True,
                                          defer_unique=True, defer_index=True, defer_check=True)

            # Need to change the field name
            if alter_field_name:
                self.execute(
                    self.sql_rename_column % {
                        'table': self.quote_name(model._meta.db_table),
                        'old_column': self.quote_name(old_field.column),
                        'new_column': self.quote_name(new_field.column),
                        'new_type': new_db_field['type'],
                    }
                )

            # Need to change the field type
            if alter_field_data_type:
                if old_field.primary_key and new_field.primary_key:
                    if isinstance(new_field, models.AutoField) and isinstance(old_field, models.IntegerField):
                        pass
                    else:
                        alter_incomming_fk_data_type = True
                # Will make default later
                if (old_field.default is not None) and (old_field.has_default()) and (old_default is not None):
                    self.execute(self.sql_drop_default % {
                        'table': self.quote_name(model._meta.db_table),
                        'column': self.quote_name(new_field.column)
                    }
                                 )
                if isinstance(new_field, models.AutoField):
                    with self.connection.cursor() as cur:
                        cur.execute(
                            'SELECT MAX( %(column)s ) from %(table)s' % {
                                'column': self.quote_name(new_field.column),
                                'table': self.quote_name(model._meta.db_table),
                            }
                        )
                        max = cur.fetchone()
                        if max[0] is None:
                            max = 0
                        else:
                            max = max[0]
                    if not isinstance(old_field, models.IntegerField):
                        sql = self.sql_alter_column_type % {
                            'table': self.quote_name(model._meta.db_table),
                            'column': self.quote_name(new_field.column),
                            'type': 'Integer'
                        }
                        self.execute(
                            self.sql_alter_column % {
                                'table': self.quote_name(model._meta.db_table),
                                'changes': sql
                            }
                        )
                    sql = self.sql_alter_column_type_from_int_to_auto % {
                        'column': self.quote_name(new_field.column),
                        'max': max + 1
                    }
                    self.execute(
                        self.sql_alter_column % {
                            'table': self.quote_name(model._meta.db_table),
                            'changes': sql
                        }
                    )
                else:
                    sql = self.sql_alter_column_type % {
                        'table': self.quote_name(model._meta.db_table),
                        'column': self.quote_name(new_field.column),
                        'type': new_db_field_type
                    }
                    self.execute(
                        self.sql_alter_column % {
                            'table': self.quote_name(model._meta.db_table),
                            'changes': sql
                        }
                    )

            # restore constraint checks
            self._restore_constraints_check(deferred_constraints, old_field, new_field, model)

        # Need to change Default
        if alter_field_default:
            if new_default is None:
                if alter_field_data_type or alter_field_nullable:
                    pass
                else:
                    self.execute(self.sql_drop_default % {
                        'table': self.quote_name(model._meta.db_table),
                        'column': self.quote_name(new_field.column)
                    }
                                 )
            else:
                sql = self.sql_alter_column_default % {
                    'column': self.quote_name(new_field.column),
                    'default': self.prepare_default(new_default),
                }
                self.execute(
                    self.sql_alter_column % {
                        'table': self.quote_name(model._meta.db_table),
                        'changes': sql
                    }
                )

        # Need to change nullability
        if alter_field_nullable:
            self._apply_nullability_change(model, new_field, make_nullable=new_field.null)

        # Need to add check constraint
        if alter_field_check_constraint and new_db_field['check']:
            self.execute(
                self.sql_create_check % {
                    'table': self.quote_name(model._meta.db_table),
                    'name': self._create_index_name(model, [new_field.column], suffix="_check"),
                    'column': self.quote_name(new_field.column),
                    'check': new_db_field['check'],
                }
            )
        # Need to change incoming foreign key field type
        incoming_relations = []
        if alter_incomming_fk_data_type:
            incoming_relations.extend(new_field.model._meta.get_all_related_objects())

        # Need to add new PK
        if alter_field_primary_key and new_field.primary_key:
            # Drop old PK if available
            try:
                self.execute(
                    self.sql_drop_pk % {
                        'table': self.quote_name(model._meta.db_table)
                    }
                )
            except:
                pass
            self.__model = model
            self.execute(
                self.sql_create_pk % {
                    'table': self.quote_name(model._meta.db_table),
                    'name': self._create_index_name(model, [new_field.column], suffix="_pk"),
                    'columns': self.quote_name(new_field.column)
                }
            )
            # Need to update all incoming relations
            incoming_relations.extend(new_field.model._meta.get_all_related_objects())
        # Need to add a unique constraint
        elif alter_field_unique and new_field.unique:
            self.execute(
                self.sql_create_unique % {
                    'table': self.quote_name(model._meta.db_table),
                    'name': self._create_index_name(model._meta.db_table, [new_field.column], suffix="_uniq"),
                    'columns': self.quote_name(new_field.column),
                }
            )
            # Need to add a index
        elif alter_field_index and new_field.db_index:
            self.execute(
                self.sql_create_index % {
                    'table': self.quote_name(model._meta.db_table),
                    'name': self._create_index_name(model, [new_field.column], suffix="_index"),
                    'columns': self.quote_name(new_field.column),
                    'extra': '',
                    'include': '',
                    'condition': ''
                }
            )
        # Update incoming FK field
        for inc_rel in incoming_relations:
            fk_db_field = inc_rel.field.db_parameters(connection=self.connection)
            fk_db_field_type = fk_db_field['type']
            sql = self.sql_alter_column_type % {
                'table': self.quote_name(model._meta.db_table),
                'column': self.quote_name(inc_rel.field.column),
                'type': fk_db_field_type,
            }
            self.execute(
                self.sql_alter_column % {
                    'table': self.quote_name(inc_rel.model._meta.db_table),
                    'changes': sql
                }
            )

        # need to reorg table if we changed the field type of fk field
        if len(incoming_relations) > 0:
            self._reorg_tables()

        # Rebuild/make FK constraint, if it have any
        if (djangoVersion[0:2] < (1, 9)):
            if new_field.rel:
                self.execute(
                    self.sql_create_fk % {
                        'table': self.quote_name(model._meta.db_table),
                        'name': self._create_index_name(model, [new_field.column], suffix="_fk"),
                        'column': self.quote_name(new_field.column),
                        'to_table': self.quote_name(new_field.rel._meta.db_table),
                        'to_column': self.quote_name(new_field.rel.get_related_field().column),
                    }
                )
        else:
            if new_field.remote_field:
                self.execute(
                    self.sql_create_fk % {
                        'table': self.quote_name(model._meta.db_table),
                        'name': self._create_index_name(self.quote_name(model._meta.db_table), [new_field.column], suffix="_fk"),
                        'column': self.quote_name(new_field.column),
                        'to_table': self.quote_name(new_field.remote_field.model._meta.db_table),
                        'to_column': self.quote_name(new_field.remote_field.get_related_field().column),
                    }
                )
        # Rebuild incoming FK constraints
        if rebuild_incomming_fk:
            if hasattr(new_field.model._meta, "get_all_related_objects"):
                for inc_rel in new_field.model._meta.get_all_related_objects():
                    self.execute(
                        self.sql_create_fk % {
                            'table': self.quote_name(inc_rel.model._meta.db_table),
                            'name': self._create_index_name(inc_rel.model, [inc_rel.field.column], suffix="_fk"),
                            'column': self.quote_name(inc_rel.field.column),
                            'to_table': self.quote_name(model._meta.db_table),
                            'to_column': self.quote_name(new_field.column),
                        }
                    )

    def alterFieldDataTypeByRemaking(self, model, old_field, new_field, strict):
        tmp_new_field = copy.deepcopy(new_field)
        tmp_new_field.column = truncate_name("%s%s" % (self.psudo_column_prefix, tmp_new_field.column),
                                             self.connection.ops.max_name_length())
        self.add_field(model, tmp_new_field)

        # Transfer data from old field to new tmp field
        self.execute("UPDATE %s set %s=%s" % (
            self.quote_name(model._meta.db_table),
            self.quote_name(tmp_new_field.column),
            self.quote_name(old_field.column)
        )
                     )
        self.remove_field(model, old_field)
        return tmp_new_field, new_field

    def add_field(self, model, field):
        self.__model = model
        notnull = not field.null
        field.null = True
        p_key = field.primary_key
        field.primary_key = False
        unique = field.unique
        field._unique = False

        super(DB2SchemaEditor, self).add_field(model, field)
        
        if field.remote_field is not None and hasattr(field.remote_field, 'through'):
            rel_condition = field.remote_field.through._meta.auto_created
        else:
            rel_condition = False

        if isinstance(field, ManyToManyField) and rel_condition:
            return
        else:
            self._reorg_tables()
        sql = None
        if notnull or unique or p_key:
            del_column = self.sql_delete_column % {
                'table': self.quote_name(model._meta.db_table), 'column': self.quote_name(field.column)
            }
            if notnull:
                field.null = False
                sql = self.sql_alter_column_not_null % {'column': self.quote_name(field.column)}
                sql = self.sql_alter_column % {'table': self.quote_name(model._meta.db_table), 'changes': sql}
                try:
                    self.execute(sql)
                    self._reorg_tables()
                except Error as e:
                    self.execute(del_column)
                    raise e
            if p_key:
                field.primary_key = True
                cur = self.connection.cursor()
                # remove other pk if available
                if hasattr(cur.connection, "primary_keys"):
                    for other_pk in cur.connection.primary_keys(True, cur.connection.get_current_schema(),
                                                                model._meta.db_table):
                        self.execute(
                            self.sql_delete_pk % {
                                'table': self.quote_name(model._meta.db_table),
                                'name': other_pk['PK_NAME']
                            }
                        )
                sql = self.sql_create_pk % {
                    'table': self.quote_name(model._meta.db_table),
                    'name': self._create_index_name(model, [field.column], suffix="_pk"),
                    'columns': self.quote_name(field.column)
                }
                try:
                    self.execute(sql)
                    self._reorg_tables()
                except Error as e:
                    self.execute(del_column)
                    raise e
            #elif unique:
            # Word reeds op veld niveau toegepast
            #field._unique = True
            #constraint_name = self._create_index_name(model, [field.column], suffix="_uniq")
            #sql = self.sql_create_unique % {
            #    'table': self.quote_name(model._meta.db_table), 'name': constraint_name,
            #    'columns': self.quote_name(field.column)
            #}
            #try:
            #    self.execute(sql)
            #    self._reorg_tables()
            #except Error as e:
            #    self.execute(del_column)
            #    raise e

    def alter_db_table(self, model, old_db_table, new_db_table):
        super(DB2SchemaEditor, self).alter_db_table(model, old_db_table, new_db_table)

    def remove_field(self, model, field):
        """
        Override remove_field to handle DB2 for i ODBC limitations.
        First removes all constraints/indexes on the field, then tries DROP COLUMN.
        Falls back to table rebuild if DROP COLUMN still fails.
        """
        # Get all fields except the one being removed
        remaining_fields = [f for f in model._meta.local_fields if f.name != field.name]
        
        if not remaining_fields:
            return super().remove_field(model, field)
        
        # First, remove all constraints and indexes on this field
        self._remove_field_constraints(model, field)
        
        # Try direct DROP COLUMN using self.execute() for compatibility
        sql = f"ALTER TABLE {self.quote_name(model._meta.db_table)} DROP COLUMN {self.quote_name(field.column)}"
        self.execute(sql)
        print(f"Successfully dropped column {field.name} from {model._meta.db_table}")

    def _remove_field_constraints(self, model, field):
        """Remove all indexes, unique constraints, and foreign keys on a field."""
        table_name = model._meta.db_table
        column_name = field.column
        
        try:
            with self.connection.cursor() as cur:
                constraints = self.connection.introspection.get_constraints(cur, table_name)
            
            for constr_name, constr_dict in constraints.items():
                if column_name in constr_dict.get('columns', []):
                    try:
                        if constr_dict.get('index'):
                            self.execute(f"DROP INDEX {self.quote_name(constr_name)}")
                        elif constr_dict.get('unique') or constr_dict.get('foreign_key'):
                            self.execute(f"ALTER TABLE {self.quote_name(table_name)} DROP CONSTRAINT {self.quote_name(constr_name)}")
                    except:
                        pass
        except Exception as e:
            print(f"WARNING: Error removing field constraints: {e}")
    
    def _remove_field_via_rebuild(self, model, field, remaining_fields):
        """
        Remove a field by rebuilding the table without using DROP COLUMN.
        This works around ODBC limitations in DB2 for i.
        Properly preserves column properties like GENERATED BY DEFAULT AS IDENTITY.
        """
        old_table = self.quote_name(model._meta.db_table)
        temp_table = self.quote_name(f"{model._meta.db_table}_tmp_{uuid.uuid4().hex[:8]}")
        
        # Get column list for data transfer (exclude the field being removed)
        select_cols = ', '.join(
            self.quote_name(f.column) for f in remaining_fields
        )
        
        # Build CREATE TABLE statement with proper column definitions
        # This preserves GENERATED BY DEFAULT AS IDENTITY and other properties
        col_defs = []
        for f in remaining_fields:
            col_name = self.quote_name(f.column)
            col_sql, _ = self.column_sql(model, f, include_default=False)
            # column_sql returns just the type definition, need to prepend column name
            col_defs.append(f"{col_name} {col_sql}")
        
        create_table_def = ', '.join(col_defs)
        
        try:
            # 1. Create new table with proper column definitions (preserves IDENTITY)
            self.execute(
                f"CREATE TABLE {temp_table} ({create_table_def})"
            )
            print(f"Created temp table {temp_table} with proper column definitions")
            
            # 2. Copy data from old table to new table
            self.execute(
                f"INSERT INTO {temp_table} ({select_cols}) SELECT {select_cols} FROM {old_table}"
            )
            print(f"Copied data from {old_table} to {temp_table}")
            
            # 3. Drop original table
            self.execute(f"DROP TABLE {old_table}")
            print(f"Dropped original table {old_table}")
            
            # 4. Rename temp table back to original
            self.execute(
                f"RENAME TABLE {temp_table} TO {old_table}"
            )
            print(f"Renamed {temp_table} to {old_table}")
            
            # 5. Restore UNIQUE and FOREIGN KEY constraints
            # (PRIMARY KEY is already preserved via the IDENTITY column definition)
            try:
                with self.connection.cursor() as cur:
                    constraints = self.connection.introspection.get_constraints(cur, model._meta.db_table)
                
                for constr_name, constr_dict in constraints.items():
                    # Skip constraints on the field being removed
                    if constr_dict.get('columns') and any(col == field.column for col in constr_dict.get('columns', [])):
                        continue
                    
                    # Skip primary key (already handled by IDENTITY)
                    if constr_dict.get('primary_key'):
                        print(f"PRIMARY KEY {constr_name} preserved via IDENTITY column")
                        continue
                    
                    # Skip foreign keys (will be handled by later migrations)
                    if constr_dict.get('foreign_key'):
                        print(f"Deferring FOREIGN KEY {constr_name} to later migration")
                        continue
                    
                    # Restore UNIQUE constraints
                    if constr_dict.get('unique'):
                        try:
                            cols = ', '.join(self.quote_name(c) for c in constr_dict.get('columns', []))
                            self.execute(
                                f"ALTER TABLE {old_table} ADD CONSTRAINT {self.quote_name(constr_name)} UNIQUE ({cols})"
                            )
                            print(f"Restored UNIQUE constraint {constr_name}")
                        except Exception as e:
                            print(f"WARNING: Could not restore UNIQUE {constr_name}: {e}")
            except Exception as e:
                print(f"WARNING: Could not restore constraints: {e}")
            
            self._reorg_tables()
            print(f"Successfully removed {field.name} from {model._meta.db_table} via table rebuild")
        except Exception as e:
            print(f"ERROR in _remove_field_via_rebuild: {e}")
            import traceback
            traceback.print_exc()
            # Try to clean up temp table if it exists
            try:
                self.execute(f"DROP TABLE {temp_table}")
            except:
                pass
            raise

    def _alter_many_to_many(self, model, old_field, new_field, strict):
        deferred_constraints = {
            'pk': {},
            'unique': {},
            'index': {},
            'check': {}
        }

        if ((old_field.remote_field is not None and hasattr(old_field.remote_field, 'through')) and
                (new_field.remote_field is not None and hasattr(new_field.remote_field, 'through'))):
            old_field_rel_through = old_field.remote_field.through
            rel_old_field = old_field.remote_field.through._meta.get_field(old_field.m2m_reverse_field_name())
            rel_new_field = new_field.remote_field.through._meta.get_field(new_field.m2m_reverse_field_name())
        else:
            rel_old_field = None
            rel_new_field = None

        if ((rel_old_field is not None) and (rel_new_field is not None)):
            with self.connection.cursor() as cur:
                constraints = self.connection.introspection.get_constraints(cur, old_field_rel_through._meta.db_table)
            for constr_name, constr_dict in constraints.items():
                if constr_dict['foreign_key'] is not None:
                    self.execute(self.sql_delete_fk % {
                        "table": self.quote_name(old_field_rel_through._meta.db_table),
                        "name": constr_name,
                    })
            self._defer_constraints_check(constraints, deferred_constraints, rel_old_field, rel_new_field,
                                          old_field_rel_through, defer_pk=True, defer_unique=True, defer_index=True)

            self._reorg_tables()
            super(DB2SchemaEditor, self)._alter_many_to_many(model, old_field, new_field, strict)
            self._restore_constraints_check(deferred_constraints, rel_old_field, rel_new_field, new_field.rel.through)

    def _reorg_tables(self):
        ...
        #if getattr(settings, 'DJANGO_ISERIES_SKIP_TABLE_REORG', False):
        #    return
#
        #checkReorgSQL = "select tabschema, tabname from sysibmadm.admintabinfo where reorg_pending = 'Y'"
        #res = []
        #reorgSQLs = []
        #with self.connection.cursor() as cursor:
        #    cursor.execute(checkReorgSQL)
        #    res = cursor.fetchall()
        #if res:
        #    for sName, tName in res:
        #        reorgSQL = '''CALL SYSPROC.ADMIN_CMD('REORG TABLE "%(sName)s"."%(tName)s"')''' % {
        #            'sName': sName, 'tName': tName
        #        }
        #        reorgSQLs.append(reorgSQL)
        #for sql in reorgSQLs:
        #    self.execute(sql)

    def _defer_constraints_check(self, constraints, deferred_constraints, old_field, new_field, model, defer_pk=False,
                                 defer_unique=False, defer_index=False, defer_check=False):
        for constr_name, constr_dict in constraints.items():
            if defer_pk and constr_dict['primary_key'] is True:
                if old_field.column in constr_dict['columns']:
                    self.execute(self.sql_delete_pk % {
                        'table': model._meta.db_table,
                        'name': constr_name
                    })
                    deferred_constraints['pk'][constr_name] = constr_dict['columns']
                    continue
            if defer_unique and constr_dict['unique'] is True:
                if old_field.column in constr_dict['columns']:
                    try:
                        self.execute(self.sql_delete_unique % {
                            'table': model._meta.db_table,
                            'name': constr_name
                        })
                        deferred_constraints['unique'][constr_name] = constr_dict['columns']
                        continue
                    except:
                        continue
            if defer_index and constr_dict['index'] is True:
                if old_field.column in constr_dict['columns']:
                    try:
                        self.execute(self.sql_delete_index % {
                            'table': model._meta.db_table,
                            'name': constr_name
                        })
                        deferred_constraints['index'][constr_name] = constr_dict['columns']
                    except:
                        pass
            if defer_check and constr_dict['check'] is True:
                if old_field.column in constr_dict['columns']:
                    self.execute(self.sql_delete_check % {
                        'table': model._meta.db_table,
                        'name': constr_name
                    })
                    deferred_constraints['check'][constr_name] = constr_dict['columns']

        return deferred_constraints

    def _restore_constraints_check(self, deferred_constraints, old_field, new_field, model):
        self.__model = model
        for pk_name, columns in deferred_constraints['pk'].items():
            self.execute(self.sql_create_pk % {
                'table': model._meta.db_table,
                'name': pk_name,
                'columns': ', '.join(column.replace(old_field.column, new_field.column) for column in columns)
            })
        for constr_name, columns in deferred_constraints['unique'].items():
            self.execute(self.sql_create_unique % {
                'table': model._meta.db_table,
                'name': constr_name,
                'columns': ', '.join(column.replace(old_field.column, new_field.column) for column in columns)
            })
        for index_name, columns in deferred_constraints['index'].items():
            self.execute(self.sql_create_index % {
                'table': model._meta.db_table,
                'name': index_name,
                'columns': ', '.join(column.replace(old_field.column, new_field.column) for column in columns),
                'extra': '',
                'include': '',
                'condition': ''
            })

    def column_sql(self, model, field, include_default=False):
        sql, params = super().column_sql(model, field, include_default=False)

        # Add FOR COLUMN only when db_system_name is meaningful and differs
        # from the logical column name.
        system_name = self._normalize_system_name(getattr(field, 'db_system_name', None))
        if system_name:
            column_name = self._base_identifier(field.column)
            if system_name != column_name.upper():
                # DB2 syntax expects FOR COLUMN before the datatype definition.
                sql = f"FOR COLUMN {system_name} {sql}"
        
        return sql, params

    def quote_value(self, value):
        if isinstance(value, (datetime.datetime, datetime.date, datetime.time, str)):
            escape_quotes = lambda s: f'{s}'.replace("'", "''")
            return f"'{escape_quotes(value)}'"
        elif isinstance(value, bool):
            return '1' if value else '0'
        elif isinstance(value, uuid.UUID):
            return f"'{value}'"
        elif isinstance(value, bytes):
            return f"BLOB(X'{value.hex()}')"
        elif isinstance(value, datetime.timedelta):
            # time intervals will be stored as double number of seconds
            return f"{value / datetime.timedelta(seconds=1)}"
        return str(value)

    def table_sql(self, model):
        sql, params = super().table_sql(model)

        # Add FOR SYSTEM NAME <system_name> right after the table name when configured.
        system_name = self._normalize_system_name(getattr(model._meta, 'db_system_name', None))
        if system_name:
            table_name = self._base_identifier(model._meta.db_table)
            if system_name != table_name.upper():
                open_paren_idx = sql.find('(')
                if open_paren_idx != -1:
                    prefix = sql[:open_paren_idx].rstrip()
                    suffix = sql[open_paren_idx:]
                    sql = f"{prefix} FOR SYSTEM NAME \"{system_name}\" {suffix}"
        
        return sql, params
    
    def _add_for_system_name(self, sql: str, model) -> str:
        """Backward-compatible hook that mirrors table_sql() behavior."""
        system_name = self._normalize_system_name(getattr(model._meta, 'db_system_name', None))
        if not system_name:
            return sql

        table_name = self._base_identifier(model._meta.db_table)
        if system_name == table_name.upper():
            return sql

        open_paren_idx = sql.find('(')
        if open_paren_idx == -1:
            return sql

        prefix = sql[:open_paren_idx].rstrip()
        suffix = sql[open_paren_idx:]
        return f"{prefix} FOR SYSTEM NAME \"{system_name}\" {suffix}"
    
    def create_model(self, model):
        """Override create_model to keep DB2 naming behavior centralized."""
        super().create_model(model)