name: Test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Provide empty .env.local
        run: touch .env.local

      - name: Run rests
        run: docker-compose run --rm tests

